---
# Values here are the same across all environments

generic-service:
  nameOverride: hmpps-registers

  image:
    repository: ghcr.io/ministryofjustice/hmpps-registers
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    tlsSecretName: hmpps-registers-cert
    modsecurity_enabled: true

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'DPS098' # Your audit service name
    PRODUCT_ID: 'DPS098'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-registers:
      API_CLIENT_ID: 'API_CLIENT_ID'
      API_CLIENT_SECRET: 'API_CLIENT_SECRET'
      SYSTEM_CLIENT_ID: 'SYSTEM_CLIENT_ID'
      SYSTEM_CLIENT_SECRET: 'SYSTEM_CLIENT_SECRET'
      APPINSIGHTS_INSTRUMENTATIONKEY: 'APPINSIGHTS_INSTRUMENTATIONKEY'
      SESSION_SECRET: 'SESSION_SECRET'

generic-prometheus-alerts:
  targetApplication: hmpps-registers
  alertSeverity: move-a-prisoner-alerts-nonprod
