import { Prison, PrisonAddress, WelshPrisonAddress } from '../../@types/prisonRegister'

export default {
  prisonAddress: ({
    id = 21,
    addressLine1 = 'Bawtry Road',
    addressLine2 = 'Hatfield Woodhouse',
    town = 'Doncaster',
    postcode = 'DN7 6BW',
    county = 'South Yorkshire',
    country = 'England',
    addressLine1InWelsh = undefined,
    addressLine2InWelsh = undefined,
    townInWelsh = undefined,
    countyInWelsh = undefined,
    countryInWelsh = undefined,
  }: Partial<PrisonAddress>): PrisonAddress =>
    ({
      id,
      addressLine1,
      addressLine2,
      town,
      postcode,
      county,
      country,
      addressLine1InWelsh,
      addressLine2InWelsh,
      townInWelsh,
      countyInWelsh,
      countryInWelsh,
    }) as PrisonAddress,

  combinedEnglishAddWelshAddress: ({
    id = 21,
    addressLine1 = '2 Knox Road',
    addressLine2 = null,
    town = 'Cardiff',
    postcode = 'CC24 0UG',
    county = 'Glamorgan',
    country = 'Wales',
    addressLine1InWelsh = 'Heol Knox',
    addressLine2InWelsh = 'Hollybush',
    townInWelsh = 'Caerdydd',
    countyInWelsh = 'Glamorgan',
    countryInWelsh = undefined,
  }: Partial<PrisonAddress>): PrisonAddress =>
    ({
      id,
      addressLine1,
      addressLine2,
      town,
      postcode,
      county,
      country,
      addressLine1InWelsh,
      addressLine2InWelsh,
      townInWelsh,
      countyInWelsh,
      countryInWelsh,
    }) as PrisonAddress,

  welshPrisonAddress: ({
    addressLine1InWelsh = 'Heol Knox',
    addressLine2InWelsh = undefined,
    townInWelsh = 'Caerdydd',
    countyInWelsh = 'Glamorgan',
    countryInWelsh = 'Cymru',
  }: Partial<WelshPrisonAddress>): WelshPrisonAddress =>
    ({
      addressLine1InWelsh,
      addressLine2InWelsh,
      townInWelsh,
      countyInWelsh,
      countryInWelsh,
    }) as WelshPrisonAddress,

  prison: ({
    prisonId = 'ALI',
    prisonName = 'Albany (HMP)',
    prisonNameInWelsh = '',
    active = true,
    male = true,
    female = true,
    contracted = false,
    lthse = false,
    addresses = [],
    types = [{ code: 'HMP', description: 'His Majesty’s Prison' }],
    operators = [{ name: 'PSP' }],
  }: Partial<Prison>): Prison =>
    ({
      prisonId,
      prisonName,
      prisonNameInWelsh,
      active,
      male,
      female,
      contracted,
      lthse,
      addresses,
      types,
      operators,
    }) as Prison,
}
