/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/court-maintenance/id/{courtId}': {
    /** Updates court information, role required is MAINTAIN_REF_DATA */
    put: operations['updateCourt']
  }
  '/court-maintenance': {
    /** Adds a new court information, role required is MAINTAIN_REF_DATA */
    post: operations['insertCourt']
  }
  '/courts': {
    /** All courts (active only) */
    get: operations['getActiveCourts']
  }
  '/courts/types': {
    /** All court types */
    get: operations['getCourtTypes']
  }
  '/courts/id/{courtId}': {
    /** Information on a specific court */
    get: operations['getCourtFromId']
  }
  '/courts/all': {
    /** All active/inactive courts */
    get: operations['getAllCourts']
  }
}

export interface components {
  schemas: {
    /** Court Update Record */
    UpdateCourtDto: {
      /** Name of the court */
      courtName: string
      /** Description of the court */
      courtDescription?: string
      /** Type of court */
      courtType:
        | 'MAGISTRATES'
        | 'CROWN'
        | 'COUNTY'
        | 'YOUTH'
        | 'OTHER'
        | 'SHERRIFS_SCOTTISH'
        | 'DISTRICT_SCOTTISH'
        | 'HIGH_COURT_SCOTTISH'
        | 'ASYLUM_IMMIGRATION'
        | 'IMMIGRATION'
        | 'COURTS_MARTIAL'
        | 'OUTSIDE_ENG_WALES'
        | 'APPEAL'
      /** Whether the court is still active */
      active: boolean
    }
    /** Court Information */
    CourtDto: {
      /** Court ID */
      courtId: string
      /** Name of the court */
      courtName: string
      /** Description of the court */
      courtDescription?: string
      /** Type of court */
      courtType:
        | 'MAGISTRATES'
        | 'CROWN'
        | 'COUNTY'
        | 'YOUTH'
        | 'OTHER'
        | 'SHERRIFS_SCOTTISH'
        | 'DISTRICT_SCOTTISH'
        | 'HIGH_COURT_SCOTTISH'
        | 'ASYLUM_IMMIGRATION'
        | 'IMMIGRATION'
        | 'COURTS_MARTIAL'
        | 'OUTSIDE_ENG_WALES'
        | 'APPEAL'
      /** Whether the court is still active */
      active: boolean
    }
    ErrorResponse: {
      status: number
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** Court Type */
    CourtTypeDto: {
      /** Type of court */
      courtType: string
      /** Description of the type of court */
      courtName: string
    }
  }
}

export interface operations {
  /** Updates court information, role required is MAINTAIN_REF_DATA */
  updateCourt: {
    parameters: {
      path: {
        courtId: string
      }
    }
    responses: {
      /** Court Information Updated */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** Information request to update court */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Incorrect permissions to make court update */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Court ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCourtDto']
      }
    }
  }
  /** Adds a new court information, role required is MAINTAIN_REF_DATA */
  insertCourt: {
    responses: {
      /** Court Information Inserted */
      201: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** Information request to add a court */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized to access this endpoint */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Incorrect permissions to make court insert */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CourtDto']
      }
    }
  }
  /** All courts (active only) */
  getActiveCourts: {
    responses: {
      /** All Active Court Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto'][]
        }
      }
    }
  }
  /** All court types */
  getCourtTypes: {
    responses: {
      /** All Types of courts returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtTypeDto'][]
        }
      }
    }
  }
  /** Information on a specific court */
  getCourtFromId: {
    parameters: {
      path: {
        courtId: string
      }
    }
    responses: {
      /** Court Information Returned */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto']
        }
      }
      /** Incorrect request to get court information */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Court ID not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** All active/inactive courts */
  getAllCourts: {
    responses: {
      /** All Court Information Returned (Active only) */
      200: {
        content: {
          'application/json': components['schemas']['CourtDto'][]
        }
      }
    }
  }
}
