# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-registers
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: registers.hmpps.service.justice.gov.uk
  cert_secret: hmpps-registers-cert
  path: /

env:
  HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
  TOKEN_VERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
  TOKEN_VERIFICATION_ENABLED: true
  COURT_REGISTER_API_URL: https://court-register.hmpps.service.justice.gov.uk

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
