---
# Environment specific values, override helm_deploy/hmpps-registers/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: registers-preprod.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    PRISON_REGISTER_API_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk
    MANAGE_USERS_API_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    INGRESS_URL: https://registers-preprod.hmpps.service.justice.gov.uk
