---
# Environment specific values, override helm_deploy/hmpps-registers/values.yaml

generic-service:
  ingress:
    host: registers.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
    PRISON_REGISTER_API_URL: https://prison-register.hmpps.service.justice.gov.uk
    MANAGE_USERS_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk
    INGRESS_URL: https://registers.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-prod
