---
# Environment specific values, override helm_deploy/hmpps-registers/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: registers-dev.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
    PRISON_REGISTER_API_URL: https://prison-register-dev.hmpps.service.justice.gov.uk

    INGRESS_URL: https://registers-dev.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
