---
# Environment specific values, override helm_deploy/hmpps-registers/values.yaml

generic-service:
  ingress:
    host: registers-preprod.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    COURT_REGISTER_API_URL: https://court-register-preprod.hmpps.service.justice.gov.uk
    PRISON_REGISTER_API_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk

    INGRESS_URL: https://registers-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
